import 'package:flutix/ui/ticketdetail.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class myticket extends StatelessWidget {
  const myticket({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: ListView(children: [
          MyTickets(),
        ]),
      ),
    );
  }
}

class MyTickets extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          height: 140,
          width: MediaQuery.of(context).size.width,
          decoration: const BoxDecoration(
              color: Color(0xFF2C1F62),
              borderRadius: BorderRadius.only(
                  bottomLeft: Radius.circular(20),
                  bottomRight: Radius.circular(20))),
          child: Column(
            children: [
              SizedBox(
                height: 30,
              ),
              Text(
                'My Tickets',
                style: GoogleFonts.raleway(
                    fontSize: 20,
                    color: Colors.white,
                    fontWeight: FontWeight.w500),
              ),
              SizedBox(height: 50),
              Container(
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  children: [
                    Text(
                      'Newest',
                      style: GoogleFonts.raleway(
                          fontWeight: FontWeight.w300,
                          color: Colors.white,
                          fontSize: 16),
                    ),
                    Text(
                      'Used',
                      style: GoogleFonts.raleway(
                          fontWeight: FontWeight.w300,
                          color: Colors.white,
                          fontSize: 16),
                    )
                  ],
                ),
              )
            ],
          ),
        ),
        SizedBox(height: 20),
        Container(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              SizedBox(
                width: 20,
              ),
              Container(
                width: 81,
                height: 79,
                decoration: const BoxDecoration(
                  image: DecorationImage(
                    image: NetworkImage("https://via.placeholder.com/81x79"),
                    fit: BoxFit.fill,
                  ),
                ),
                child: GestureDetector(
                  onTap: () {
                    // Navigasi ke halaman detail saat gambar di-klik
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => ticketdetail()),
                    );
                  },
                ),
              ),
              SizedBox(width: 10),
              Container(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    Text(
                      'The Avengers',
                      style: GoogleFonts.raleway(
                          fontSize: 20,
                          fontWeight: FontWeight.w500,
                          color: Colors.black),
                    ),
                    Text(
                      'Action - English',
                      style: GoogleFonts.raleway(
                          fontSize: 16,
                          fontWeight: FontWeight.w300,
                          color: const Color.fromARGB(255, 160, 160, 160)),
                    ),
                    Text(
                      'XXI Big Mall Samarinda',
                      style: GoogleFonts.raleway(
                          fontSize: 16,
                          fontWeight: FontWeight.w300,
                          color: const Color.fromARGB(255, 160, 160, 160)),
                    ),
                  ],
                ),
              )
            ],
          ),
        ),
      ],
    );
  }
}
