import 'package:flutix/ui/ticketdetail.dart';
import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class myticket extends StatelessWidget {
  const myticket({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MyTickets(),
        ]),
      ),
    );
  }
}

class MyTickets extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 834,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 191,
                top: 102,
                child: Container(
                  width: 110,
                  height: 59.30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 110,
                          height: 59.30,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(7)),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 28,
                        top: 22,
                        child: SizedBox(
                          width: 54,
                          height: 15,
                          child: Text(
                            'Used',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 102,
                child: Container(
                  width: 110,
                  height: 59.30,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 110,
                          height: 59.30,
                          decoration: ShapeDecoration(
                            color: Color(0xFFD9D9D9),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(7)),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 28,
                        top: 22,
                        child: SizedBox(
                          width: 54,
                          height: 15,
                          child: Text(
                            'New',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 193,
                child: Container(
                  width: 267,
                  height: 79,
                  child: Stack(
                    children: [
                      const Positioned(
                        left: 79,
                        top: 28,
                        child: SizedBox(
                          width: 155,
                          height: 23,
                          child: Text(
                            'Sunday 30, 15.oo',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 51,
                        child: SizedBox(
                          width: 172,
                          height: 23,
                          child: Text(
                            'XXI Big Mall Samarinda',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 4,
                        child: SizedBox(
                          width: 131,
                          height: 23,
                          child: Text(
                            'The Avengers',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 18,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 81,
                          height: 79,
                          decoration: const BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/81x79"),
                              fit: BoxFit.fill,
                            ),
                          ),
                          child: GestureDetector(
                            onTap: () {
                              // Navigasi ke halaman detail saat gambar di-klik
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => ticketdetail()),
                              );
                            },
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 401,
                child: Container(
                  width: 267,
                  height: 79,
                  child: Stack(
                    children: [
                      const Positioned(
                        left: 79,
                        top: 28,
                        child: SizedBox(
                          width: 155,
                          height: 23,
                          child: Text(
                            'Sunday 30, 15.oo',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 51,
                        child: SizedBox(
                          width: 172,
                          height: 23,
                          child: Text(
                            'XXI Big Mall Samarinda',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 4,
                        child: SizedBox(
                          width: 131,
                          height: 23,
                          child: Text(
                            'The Avengers',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 18,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 81,
                          height: 79,
                          decoration: const BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/81x79"),
                              fit: BoxFit.fill,
                            ),
                          ),
                          child: GestureDetector(
                            onTap: () {
                              // Navigasi ke halaman detail saat gambar di-klik
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => ticketdetail()),
                              );
                            },
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 505,
                child: Container(
                  width: 267,
                  height: 182,
                  child: Stack(
                    children: [
                      const Positioned(
                        left: 79,
                        top: 28,
                        child: SizedBox(
                          width: 155,
                          height: 23,
                          child: Text(
                            'Sunday 30, 15.oo',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 51,
                        child: SizedBox(
                          width: 172,
                          height: 23,
                          child: Text(
                            'XXI Big Mall Samarinda',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 4,
                        child: SizedBox(
                          width: 131,
                          height: 23,
                          child: Text(
                            'The Avengers',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 18,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 81,
                          height: 79,
                          decoration: const BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/81x79"),
                              fit: BoxFit.fill,
                            ),
                          ),
                          child: GestureDetector(
                            onTap: () {
                              // Navigasi ke halaman detail saat gambar di-klik
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => ticketdetail()),
                              );
                            },
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 103,
                        child: Container(
                          width: 267,
                          height: 79,
                          child: Stack(
                            children: [
                              const Positioned(
                                left: 79,
                                top: 28,
                                child: SizedBox(
                                  width: 155,
                                  height: 23,
                                  child: Text(
                                    'Sunday 30, 15.oo',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Raleway',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 95,
                                top: 51,
                                child: SizedBox(
                                  width: 172,
                                  height: 23,
                                  child: Text(
                                    'XXI Big Mall Samarinda',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 16,
                                      fontFamily: 'Raleway',
                                      fontWeight: FontWeight.w400,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              const Positioned(
                                left: 95,
                                top: 4,
                                child: SizedBox(
                                  width: 131,
                                  height: 23,
                                  child: Text(
                                    'The Avengers',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 18,
                                      fontFamily: 'Raleway',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 81,
                                  height: 79,
                                  decoration: const BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                          "https://via.placeholder.com/81x79"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                  child: GestureDetector(
                                    onTap: () {
                                      // Navigasi ke halaman detail saat gambar di-klik
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                ticketdetail()),
                                      );
                                    },
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 297,
                child: Container(
                  width: 267,
                  height: 79,
                  child: Stack(
                    children: [
                      const Positioned(
                        left: 79,
                        top: 28,
                        child: SizedBox(
                          width: 155,
                          height: 23,
                          child: Text(
                            'Sunday 30, 15.oo',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 51,
                        child: SizedBox(
                          width: 172,
                          height: 23,
                          child: Text(
                            'XXI Big Mall Samarinda',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 16,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 95,
                        top: 4,
                        child: SizedBox(
                          width: 131,
                          height: 23,
                          child: Text(
                            'The Avengers',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 18,
                              fontFamily: 'Raleway',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 81,
                          height: 79,
                          decoration: const BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/81x79"),
                              fit: BoxFit.fill,
                            ),
                          ),
                          child: GestureDetector(
                            onTap: () {
                              // Navigasi ke halaman detail saat gambar di-klik
                              Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (context) => ticketdetail()),
                              );
                            },
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 127,
                top: 50,
                child: SizedBox(
                  width: 119,
                  height: 60,
                  child: Text(
                    'My Tickets',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Raleway',
                      fontWeight: FontWeight.w700,
                      height: 0,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 287,
                top: 91,
                child: Container(
                  width: 100,
                  height: 100,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
